config/routes.rb
Rails.application.routes.draw do

  root :to => 'questions#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :users
  resources :searches

  resources :questions do
    resources :answers, :except => [:index]
  end
  resources :answers, :except => [:index] do
    resources :votes, :except => [:index]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base

  validates :text, :presence => true
  validates :user_id, :presence => true
  validates :question_id, :presence => true

  belongs_to :user
  belongs_to :question
  has_many :votes

  def score
    self.votes.count
  end



end

app/models/question.rb
class Question < ActiveRecord::Base

  validates_presence_of :user_id, :text

  belongs_to :user
  has_many :answers
  has_many :votes



end

app/models/search.rb
class Search

  def self.find(query)
    Question.basic_search(query) + Answer.basic_search(query)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :name, :presence => true
  validates_uniqueness_of :email, :presence => { :on => :create }
  validates :password_confirmation, :presence => { :on => :create }

  has_many :questions
  has_many :answers
  has_many :votes

end

app/models/vote.rb
class Vote < ActiveRecord::Base

  validates :user_id, :presence => true
  validates :answer_id, :presence => true

  belongs_to :user
  belongs_to :answer

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    if @answer.save
      respond_to do |format|
        format.html { redirect_to question_url }
        format.js
      end
    end
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update(params[:answer])
    respond_to do |format|
      format.html { redirect_to question_url }
      format.js
    end
  end

  private
  def answer_params
    params.require(:answer).permit(:text, :question_id).merge(user_id: current_user.id, question_id: @question.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :authorize, only: [:edit, :update]


  def index
    @question = Question.new
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
       respond_to do |format|
        format.html { redirect_to question_url }
        format.js
      end
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update(params[:question])
    respond_to do |format|
      format.html { redirect_to question_url }
      format.js
    end
  end

private
  def question_params
    params.require(:question).permit(:text).merge(:user_id => current_user.id)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    @results = Search.find(params[:query])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def new
    @vote = Vote.new
  end

  def create
    @vote = current_user.votes.new(vote_params)
    if @vote.save
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  private
  def vote_params
    params.permit(:user_id, :answer_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<div class="answer_form">
<%= form_for [@question, @answer], remote: true do |f| %>
  <%= f.text_area :text, cols: 50, rows: 5 %><br>
  <%= f.submit :class => "btn btn-default btn-xs" %>
<% end %>
</div>

app/views/answers/create.js.erb
$('#new_answer').append("<li><%= answer.text %><%= answer.score %><%= j button_to 'Upvote', answer_votes_path(@answer), :params => { :answer_id => @answer.id }, :method => 'post' %><%= @answer.text %></li>");
$('#answer_form').show();

app/views/answers/show.html.erb
<%= render 'form' %>
<ul id="questions">
  <% @questions.each do |question| %>
  <li><%= link_to question.text, question_path(question), :method => post %></li>
  <% end %>
</ul>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" <%= link_to "Stack Overflow", questions_path %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Ask Question</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search" action="/searches" method="get">
        <div class="form-group">
          <input type="text" name="query" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <div class="navbar-form navbar-right">
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      <% end %>
    </div>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%= render 'layouts/header' %>

  <div class="container">


  <%= flash[:alert] %>
  <%= flash[:notice] %>
  <%= yield %>

</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, remote: true do |f| %>
  <%= f.text_field :text %><br>
  <%= f.submit :class => "btn btn-default btn-xs" %><br>
<% end %>

app/views/questions/_question.html.erb
<li><%= link_to question.text, question_path(question) %></li>

app/views/questions/create.js.erb
$('#new_link').show();
$('#questions').append('<%= j render(@question) %>');


// render 'question', question: @question

app/views/questions/index.html.erb
<%= render 'form' %><br>

<ul id="questions">
  <%= render @questions %>
</ul>

app/views/questions/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/questions/show.html.erb
<h1><%= @question.text %></h1>


<ul id="new_answer">
  <% @question.answers.each do |answer| %>
  <li><%= answer.text %><br>
  <div class="row">
    <div class="col-sm-2 col">
  <%= answer.score %> - <%= link_to "Upvote", answer_votes_path(answer), :params => { :answer_id => answer.id }, :method => "post", :class => "btn btn-default btn-xs test" %>
  </div>
  </div>
  </li>
  <% end %>
</ul>


<ul id="answer_form">
  <%= render  "answers/form", answer: @answer %>
</ul>

app/views/searches/_search.html.erb
<li><%= link_to question_path(@question, @answer) %></li>

app/views/searches/index.html.erb
<h1><% @results.each do |result| %></h1>
<li><%= link_to result.text, question_path(result) %></li>
<% end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>